version: "3"

services:
  backend:
    build: .
    container_name: be-express-app
    ports:
      - "8002:5000"
    environment:
       - MONGO_URI=mongodb://mongo-db:27017/tokoku
    depends_on:
      - mongo-db  # Ganti dari "mongo" ke "mongo-db"
    networks:
      - app-network

  mongo-db:  
    image: mongo:4
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
